name: bricolage
dependencies:
- appnope=0.1.0=py27_0
- cython=0.23.4=py27_0
- decorator=4.0.4=py27_0
- docopt=0.6.2=py27_0
- enum34=1.0.4=py27_0
- fastcache=1.0.2=py27_0
- hdf5=1.8.15.1=2
- ipykernel=4.1.1=py27_0
- ipython=4.0.0=py27_1
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_core=4.0.6=py27_0
- markupsafe=0.23=py27_0
- mistune=0.7.1=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.10=py27_0
- notebook=4.0.6=py27_0
- numexpr=2.4.4=np110py27_0
- numpy=1.10.1=py27_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- ptyprocess=0.5=py27_0
- py=1.4.30=py27_0
- pygments=2.0.2=py27_0
- pytables=3.2.2=np110py27_0
- pytest=2.8.1=py27_0
- python=2.7.10=2
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyzmq=14.7.0=py27_1
- readline=6.2=2
- setuptools=18.5=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_0
- sqlalchemy=1.0.9=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- sympy=0.7.6.1=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.2.1=py27_1
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - args==0.1.0
  - backports.ssl-match-hostname==3.4.0.2
  - causalinfo==1.1.0
  - clint==0.5.1
  - invoke==0.11.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - pathlib==1.0.1
  - pygraphviz==1.3.1
  - tables==3.2.2

